# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title_small: MInU
title: Medical Informatics
title_small: Medical Informatics
author: cmi
#email: cmi.uzh@gmail.com
description: University of Zurich & University Hospital of Zurich
description_small: UZH+USZ
#>- # this means to ignore newlines until "baseurl:"
baseurl: "/cmi-website" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: CMI_UZH
github_username:  uzh-dqbm-cmi
repository: "CMI-UZH/cmi-website"

#author:
#  name: "Krauthhammer Lab"
#  avatar: "/assets/images/uzh.jpg"
#  bio: "Biomedical informatics  and machine learning research in healthcare."
#  location: "Zurich"
#  links:
#    - label: "UZH Homepage"
#      icon: "fas fa-fw fa-link"
#      url: "https://www.cmi.uzh.ch/en.html"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/uzh-dqbm-cmi"

# Build settings
markdown: kramdown
#theme: jekyll-theme-clean-blog
remote_theme: "BlackrockDigital/startbootstrap-clean-blog-jekyll"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-include-cache

include:
  - images

# pagination settings from MinimalMistakes
paginate: 5 # amount of posts to show
paginate_path: /posts/page:num/

defaults:
  - scope:
      path: "" # empty string means all files
    values:
      author_profile: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
